# Generated by Django 2.1 on 2018-08-28 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20180828_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='market_cap',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=15, null=True),
        ),
    ]
