# Generated by Django 2.1 on 2018-08-28 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20180828_0812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='market_cap',
            field=models.DecimalField(decimal_places=5, max_digits=25, null=True),
        ),
    ]
